name: CFDeployment
on: pull_request
env:
    TF_STATE_BUCKET_NAME: "new-tfstate-bucket5878"
    GCP_PROJECT_ID: "databricks-new"
    RUN_REGION: "us-central1"
jobs:
  cf-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_TF_SECRET }}'

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME"
        working-directory: ./tfScripts/
        
      - name: Terraform plan
        id: plan
        run: |-
          terraform plan \
           -var="project_id=$GCP_PROJECT_ID" \
           -var="version_id=$(gcloud functions describe new-function2|grep versionId|sed 's/\://'g)"\
           -out=PLAN
        working-directory: ./tfScripts/

      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./tfScripts/
        
      - run: terraform output
        working-directory: ./tfScripts/

      - uses: 'google-github-actions/setup-gcloud@v1'

        
